src/objects/ConfigurazioneGeolocalizzazione__mdt.object
<CustomObject>
    <fields>
        <fullName>CityField__c</fullName>
        <label>City Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CountryField__c</fullName>
        <label>Country Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GeocodingAddressFormat__c</fullName>
        <label>Geocoding Address Format</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ar</fullName>
                    <label>Arabic</label>
                </value>
                <value>
                    <fullName>nl</fullName>
                    <label>Dutch</label>
                </value>
                <value>
                    <fullName>de</fullName>
                    <label>German</label>
                </value>
                <value>
                    <fullName>en</fullName>
                    <default>true</default>
                    <label>English</label>
                </value>
                <value>
                    <fullName>en-GB</fullName>
                    <label>English (Great Britain)</label>
                </value>
                <value>
                    <fullName>fr</fullName>
                    <label>French</label>
                </value>
                <value>
                    <fullName>it</fullName>
                    <label>Italian</label>
                </value>
                <value>
                    <fullName>pt</fullName>
                    <label>Portuguese</label>
                </value>
                <value>
                    <fullName>es</fullName>
                    <label>Spanish</label>
                </value>
                <value>
                    <fullName>ru</fullName>
                    <label>Russian</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GeocodingStatusField__c</fullName>
        <label>Geocoding Status Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastGeocodingAttemptDateField__c</fullName>
        <label>Last Geocoding Attempt Date Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastGeocodingDateField__c</fullName>
        <label>Last Geocoding Date Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NormalizedAdministrativeAreaLv1__c</fullName>
        <label>Normalized Administrative Area (lv. 1)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NormalizedAdministrativeAreaLv2__c</fullName>
        <label>Normalized Administrative Area (lv. 2)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NormalizedCityField__c</fullName>
        <label>Normalized City Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NormalizedCountryCodeField__c</fullName>
        <label>Normalized Country Code Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NormalizedFullAddressField__c</fullName>
        <label>Normalized Full Address Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NormalizedLatitudeField__c</fullName>
        <label>Normalized Latitude Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NormalizedLongitudeField__c</fullName>
        <label>Normalized Longitude Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NormalizedStreetField__c</fullName>
        <label>Normalized Street Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NormalizedStreetNumberField__c</fullName>
        <label>Normalized Street Number Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NormalizedZipcodeField__c</fullName>
        <label>Normalized Zipcode Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ObjectAPIName__c</fullName>
        <label>Object API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>StreetField__c</fullName>
        <label>Street Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZipcodeField__c</fullName>
        <label>Zipcode Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Configurazione Geolocalizzazione</label>
    <pluralLabel>Configurazione Geolocalizzazioni</pluralLabel>
</CustomObject>

src/objects/GoogleMapsGeocoding__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>ServerKey__c</fullName>
        <label>Server Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GoogleMapsGeocoding</label>
</CustomObject>

src/classes/GeocodingUtils.cls
// Apex class the handles the geocoding request for an object
public class GeocodingUtils {

    // Base endpoint URL. Il formato degli indirizzi ritornato è sempre quello italiano
    public static String baseEndpoint = 'https://maps.googleapis.com/maps/api/geocode/json';
    public static String geolocationConfig_geocodingFormat = 'GeocodingAddressFormat__c';
    public static String[] geolocationConfig_InputAddressFields = new String[]{'StreetField__c', 'CityField__c', 'ZipcodeField__c', 'CountryField__c'};
    public static String[] geolocationConfig_OutputAddressFields = new String[]{'NormalizedStreetField__c', 'NormalizedStreetNumberField__c', 'NormalizedCityField__c', 'NormalizedZipcodeField__c',
        'NormalizedAdministrativeAreaLv1__c', 'NormalizedAdministrativeAreaLv2__c', 'NormalizedCountryCodeField__c', 'NormalizedFullAddressField__c'};
    public static String geolocationConfig_OutputLatitudeField = 'NormalizedLatitudeField__c';
    public static String geolocationConfig_OutputLongitudeField = 'NormalizedLongitudeField__c';
    public static String geolocationConfig_AttemptDateField = 'LastGeocodingAttemptDateField__c';
    public static String geolocationConfig_DateField = 'LastGeocodingDateField__c';
    public static String geolocationConfig_StatusField = 'GeocodingStatusField__c';
    public static Map<String, String> geolocationMapping = new Map<String, String>{
        'route' => 'NormalizedStreetField__c',
        'street_number' => 'NormalizedStreetNumberField__c',
        'locality' => 'NormalizedCityField__c',
        'postal_code' => 'NormalizedZipcodeField__c',
        'administrative_area_level_1' => 'NormalizedAdministrativeAreaLv1__c',
        'administrative_area_level_2' => 'NormalizedAdministrativeAreaLv2__c',
        'country' => 'NormalizedCountryCodeField__c',
        'formatted_address' => 'NormalizedFullAddressField__c'
    };

    // Geocoding function
    public static SObject geocodeObject(SObject obj, String sObjectType){

        // Compute the query to get the fields API names from the custom metadata
        String configQuery = 'SELECT ' + String.join(geolocationConfig_InputAddressFields, ', ') + ', ' + String.join(geolocationConfig_OutputAddressFields, ', ') + ', ' +
            geolocationConfig_OutputLatitudeField + ', ' + geolocationConfig_OutputLongitudeField + ', ' + geolocationConfig_AttemptDateField + ', ' + geolocationConfig_DateField + ', ' +
            geolocationConfig_geocodingFormat + ' ' +
            'FROM ConfigurazioneGeolocalizzazione__mdt ' +
            'WHERE ObjectAPIName__c = \'' + sObjectType + '\' ';
        // Get the geolocation configuration
        ConfigurazioneGeolocalizzazione__mdt geolocationConfig = Database.query(configQuery);

        // Get the google server key from a custom setting and the full address chaining the fields given in input
        String apiKey = GoogleMapsGeocoding__c.getOrgDefaults().ServerKey__c;
        String fullAddress = GeocodingUtils.returnFullAddress(obj, geolocationConfig);
        // Encode the full address and compute the complete the endpoint
        String addressEncoded = EncodingUtil.urlEncode(fullAddress, 'UTF-8');
        // Address format language
        String formatLanguage = (String)geolocationConfig.get(geolocationConfig_geocodingFormat);
        // Compute the complete endpoint URL
        String endpointUrl = baseEndpoint +'?language=' + formatLanguage + '&key=' + apiKey + '&address=' + addressEncoded;

        // Send the request to the geocoding service and get the response (in test classes the reponse is fixed)
        HttpRequest req = new HttpRequest();
        HttpResponse res = new HttpResponse();
        Http http = new Http();
        req.setEndpoint(endpointUrl);
        req.setMethod('GET');
        try {
            if(!Test.isRunningTest()) {
                res = http.send(req);
            } else {
                res.setBody(GeocodeBeanTest.getJson());
            }
        } catch(System.CalloutException e) {
            System.debug('Exception: ' + e);
        }
        
        // Deserialize the response throught the GeocodeBean class
        GeocodeBean bean = (GeocodeBean) System.JSON.deserialize(res.getBody(), GeocodeBean.class);
        // If there is one and only one result the geocoding request is considered successful, otherewise we save an error on the record
        if(bean.results.size() == 1) {
            // Initialize all the fileds in which the process will store the normalized fields
            for(String configField : geolocationConfig_OutputAddressFields){
                if(!String.isEmpty((String)geolocationConfig.get(configField))){
                    obj.put((String)geolocationConfig.get(configField), '');
                }
            }
            obj.put((String)geolocationConfig.get(geolocationConfig_OutputLatitudeField), null);
            obj.put((String)geolocationConfig.get(geolocationConfig_OutputLongitudeField), null);

            // Save the address components obtained from the geocoding service (if the corresponded field is specified)
            for(GeocodeBean.AddressComponents comp : bean.results[0].address_components) {
                Set<String> componentTypes = new Set<String>(comp.types);
                for(String type : geolocationMapping.keySet()){
                    if(componentTypes.contains(type) && !String.isEmpty((String)geolocationConfig.get(geolocationMapping.get(type)))) {
                        obj.put((String)geolocationConfig.get(geolocationMapping.get(type)), comp.short_name);
                    }
                }
            }
            // If it is specified the filed, save the formatted address
            if(!String.isEmpty((String)geolocationConfig.get(geolocationMapping.get('formatted_address')))){
                obj.put((String)geolocationConfig.get(geolocationMapping.get('formatted_address')), bean.results[0].formatted_address);
            }
            // Save the latitude and longitude
            obj.put((String)geolocationConfig.get(geolocationConfig_OutputLatitudeField), bean.results[0].geometry.location.lat);
            obj.put((String)geolocationConfig.get(geolocationConfig_OutputLongitudeField), bean.results[0].geometry.location.lng);
            // If it is specified, save the date and time of the successful geolocalization
            if(!String.isEmpty((String)geolocationConfig.get(geolocationConfig_DateField))){
                obj.put((String)geolocationConfig.get(geolocationConfig_DateField), System.now());
            }
        }
        // Save the date and time of this geolocalization attempt
        if(!String.isEmpty((String)geolocationConfig.get(geolocationConfig_AttemptDateField))){
            obj.put((String)geolocationConfig.get(geolocationConfig_AttemptDateField), System.now());
        }
        // Save the status of this geolocalization attempt
        if(!String.isEmpty((String)geolocationConfig.get(geolocationConfig_StatusField))){
            String status = bean.results.size() == 1 ? bean.status : 'TOO_MANY_RESULTS';
            obj.put((String)geolocationConfig.get(geolocationConfig_StatusField), status);
        }
        // Update and return the object
        update obj;
        return obj;
    }

    // Private function to compute the full address
    private static String returnFullAddress(SObject obj, ConfigurazioneGeolocalizzazione__mdt addressFields) {
        String fullAddress = '';
        for(String configField : geolocationConfig_InputAddressFields){
            String field = (String)addressFields.get(configField);
            if(String.isNotBlank((String)obj.get(field))) {
                fullAddress += (String)obj.get(field) + ' ';
            }
        }
        return fullAddress;
    }
}